name: deploy
on: [push]
jobs:
  continuous-deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf soccer_bot_backend
          git clone git@github.com:pzandre/soccer_bot_backend
          cp python.env soccer_bot_backend
          cd soccer_bot_backend
          git submodule init
          git submodule update
          docker-compose stop
          docker-compose build
          docker-compose up -d
